name: build

on:
  push:

jobs:
  build:
    name: "Build and push Docker image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: basename "${GITHUB_REF}" > tag
      - run: TAG=$(cat tag) make
      - run: TAG=$(cat tag) make push
