name: build-all

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  master:
    name: "Build and push master"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: "master"
      - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        name: Docker login
      - name: Build image
        run: |
          for try in 1 2 3; do
              if make push TAG="5.0"; then
                  exit 0
              fi
          done
          exit 1
      - name: Push image
        run: make push TAG="master"

  branch-5_0:
    name: "Build and push 5.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: "5.0"
      - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: |
          for try in 1 2 3; do
              if make push TAG="5.0"; then
                  exit 0
              fi
          done
          exit 1
        
  branch-4_1:
    name: "Build and push 4.1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: "4.1"
      - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: |
          for try in 1 2 3; do
              if make push TAG="4.1"; then
                  exit 0
              fi
          done
          exit 1
        
